name: Fast stability tests

on:
  push:

jobs:
  race_test:
    runs-on: ubuntu-20.04
    name: Fast stability tests on ${{ github.ref }}
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install kaspad
        #working-directory: kaspad
        run: |
          echo $PWD
          ls -la
          cd kaspad
          ls -la
          git status
          #echo git checkout "${GITHUB_REF##*/}"
          #git checkout "${GITHUB_REF##*/}"
          #git status
          #go install ./...

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Stability fast test
        timeout-minutes: 720
        run: kaspad/stability-tests/install_and_test.sh
