name: Fast stability tests

on:
  push:

jobs:
  race_test:
    runs-on: ubuntu-20.04
    name: Fast stability tests on ${{ matrix.branch }}
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: kaspanet/kaspad
          path: kaspad

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install kaspad
        shell: bash
        working-directory: ./kaspad
        run: |
          git checkout "${{ env.run_on }}"
          git status
          go install ./...


      - name: Install golint
        shell: bash
        run: |
          go get -u golang.org/x/lint/golint

      - name: Stability fast test
        shell: bash
        working-directory: ./kaspad/stability-tests
        timeout-minutes: 720
        run: ./install_and_test.sh
