name: Fast stability tests

on:
  push:

jobs:
  race_test:
    runs-on: ubuntu-20.04
    name: Fast stability tests on ${{ matrix.branch }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install kaspad
        shell: bash
        #working-directory: ./kaspad
        run: |
          echo $PWD
          ls -la
          cd kaspad
          ls -la
          git status
          #echo git checkout "${GITHUB_REF##*/}"
          #git checkout "${GITHUB_REF##*/}"
          #git status
          #go install ./...


      - name: Install golint
        shell: bash
        run: |
          go get -u golang.org/x/lint/golint

      - name: Stability fast test
        shell: bash
        working-directory: ./kaspad/stability-tests
        timeout-minutes: 720
        run: ./install_and_test.sh
